# Base URLs for the API
base_url: "https://reqres.in/api"  # The base URL for the test API
wiremock_url: "http://localhost:8080"  # Mock base URL

# API Endpoints (relative to the base_url)
user_url: "${base_url}/users"
auth_url: "${base_url}/login"
product_url: "${base_url}/products"

# Authentication Token (if needed for API requests)
auth_token: "your_token_here"