# Base URLs for the API
base_urls:
  qa: "https://reqres.in/api"   # QA environment base URL
  staging: "http://staging.reqres.in/api"   # Staging environment base URL
  demo: "http://demo.reqres.in/api"   # Demo environment base URL

wiremock_url: "http://localhost:8080"  # Mock base URL

# API Endpoints
endpoints:
  base_api:
    login: "/login"
    users: "/users"
    users_page: "/users?page={page}"
    users_by_id: "/users/{user_id}"
    fetch_data: "/fetch-data"
    unknown: "/unknown"
    unknown_by_id: "/unknown/{resource_id}"
  wiremock:
    admin_dashboard: "/admin/dashboard"
    mocked_user: "/mocked-user"
    admin: "/admin"

# WebSocket Service URL
websocket_url: "wss://echo.websocket.events"  # WebSocket Echo Service URL